### ISSUE TITLE
[NHÓM 12] LỖI CHỨC NĂNG - KHÔNG DÙNG ĐƯỢC CHỨC NĂNG TÌM KIẾM http://www.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161022848** [UEHMonQAQC/K42#110]
a. Web Browser:  Google Chrome Version 70.0.3538.77 
b. Các bước để phát hiện lỗi: 
i. #1: Truy cập vào trang web http://www.ueh.edu.vn/ 
ii. #2: Chọn sang phiên bản tiếng anh bằng cách nhấp vào “English” phía bên phải trang web dưới icon “cuốn lịch”
iii. #3: Nhập nội dung vào ô tìm kiếm phía trên góc phải của web
iv. #4: Nhấn Enter hoặc click vào kính lúp để tìm
c. Kết quả thực tế: Không sử dụng được chức năng tìm kiếm
 
![image](https://user-images.githubusercontent.com/44227075/47997400-3f354100-e12e-11e8-9302-14a595e6558a.png)

d. Kết quả mong đợi: Sử dụng được chức năng tìm kiếm

**Comment by 31161024766** [comment]
Nhóm bị trùng lỗi 139 của K41 nhé
https://github.com/UEHMonQAQC/K41/issues/139
