### ISSUE TITLE
[Nhóm #3] Lỗi chức năng - Lỗi link liên kết - ở trang http://digital.lib.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161023717** [UEHMonQAQC/K42#114]
a.Web browser : Chorme - Phiên bản 70.0.3538.77
b.Các bước để phát hiện lỗi:
i.#1: Truy cập trang http://digital.lib.ueh.edu.vn/
ii.#2: Kéo xuống cuối trang
iii.#3: Nhấp vào biểu tượng **Twitter** được đánh dấu
 
<img width="960" alt="buttom" src="https://user-images.githubusercontent.com/44312505/48038252-72b1b300-e1a2-11e8-890e-4724cfdca746.png">

c. Kết quả thực tế: Đường link được liên kết lại là trang http://digital.lib.ueh.edu.vn/
 
<img width="960" alt="digital" src="https://user-images.githubusercontent.com/44312505/48038343-c3c1a700-e1a2-11e8-97ed-17cbd1697a0b.png">

d.Kết quả mong đợi: Truy cập được vào trang Twitter.

**Comment by khueyeuqaqc** [comment]
Xin chào! 
Mình đã kiểm tra và lỗi đúng như mô tả. Tuy nhiên, lỗi này bị trùng với khoá K41 rồi :(
