### ISSUE TITLE
[Nhóm#9] Lỗi chức năng - LỖI KHÔNG ĐỔI ĐƯỢC MẬT KHẨU TRANG LMS - ở trang https://lms.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161021925** [UEHMonQAQC/K42#124]
a. Web Browser: ‎Cốc Cốc 72.4.208
b. Các bước để phát hiện lỗi: 
i. #1: Đăng nhập vào trang http://lms.ueh.edu.vn/  bằng tài khoản sinh viên
ii. #2: Mở tùy chỉnh profile cá nhân ở mũi tên kế bên ảnh đại diên của góc bên phải
iii. #3: Chọn khung Tùy chọn
iv. #4: Chọn Đổi mật khẩu
v. #5: Chọn Lưu những thay đổi
c. Kết quả thực tế 
- Không thể thay đổi mật khẩu
![image](https://user-images.githubusercontent.com/44269018/48041697-f5416f00-e1b0-11e8-8a5a-675a7d630878.png)
d. Kết quả mong đợi 
-  Thay đổi được và đăng nhập thành công với Password mới

**Comment by 31161026102** [comment]
Sau khi kiểm tra , mình kết luận lỗi này không hợp lệ do trùng với lỗi #14 của K41.
