### ISSUE TITLE
[Nhóm#9] Lỗi chức năng - Lỗi trang web bị lỗi - ở trang http://ctct.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161021925** [UEHMonQAQC/K42#126]
a. Web Browser: Google Chrome 70.0.3538.67
b. Các bước để phát hiện lỗi: 
i. #1: Đăng nhập vào trang http://ctct.ueh.edu.vn/
ii. #2: Nhấn vào mục liên kết
iii. #3: Chọn mục bộ giáo dục và đào tạo
c. Kết quả thực tế: trang web bị lỗi
![image](https://user-images.githubusercontent.com/44269018/48041782-64b75e80-e1b1-11e8-8cbe-d073f8cb253a.png)
d. Kết quả mong đợi: hiện ra trang web

**Comment by 31161026102** [comment]
Mình đã kiểm tra và kết luận lỗi này không hợp lệ.
Trùng với lỗi #29 của K41.
