### ISSUE TITLE
[Nhóm#9] Lỗi chức năng - Lỗi không thoát ra trang cũ được - ở trang http://ctct.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161021925** [UEHMonQAQC/K42#127]
a. Web Browser: Google Chrome 70.0.3538.67
b. Các bước để phát hiện lỗi: 
i. #1: Đăng nhập vào trang http://ctct.ueh.edu.vn/
ii. # 2: Kéo xuống phần “ Công tác đánh giá kết quả rèn luyện” chọn bài viết “Công nhận kết quả rèn luyện sinh viên K41, 42, 43 ĐHCQ - Học kỳ đầu năm 2018” 
iii. #3: Kéo xuống cuối bài viết chọn năm 2017,  bấm tra cứu và chọn bài viết bất kì 
iv. #4: Bấm trở về bài viết trước xuất hiện lỗi
c. Kết quả thực tế: khi người dùng muốn trở về trang thông tin của năm 2017 thì không được nhưng nếu kích chuột trở về 2 lần thì sẽ trở về trang ở bước #3 điều này gây khó khăn cho người sử dụng khi tìm kiếm các thông tin cũ
![image](https://user-images.githubusercontent.com/44269018/48041813-8dd7ef00-e1b1-11e8-8438-064ae85d0940.png)
d. Kết quả mong muốn: thoát ra được bài viết và trở về trang thông tin năm 2017

**Comment by 31161026102** [comment]
Mình đã kiểm tra và xác nhận lỗi này không hợp lệ.
Các bạn click chuột 2 lần vào trở về thì có thể thoát ra  bài viết và trở về bài viết ban đầu.
