### ISSUE TITLE
[NHÓM 9] – Lỗi chức năng – Lỗi hiển thị nội dung không đúng http://ctct.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161021925** [UEHMonQAQC/K42#137]
a. Web Browser: Google Chrome 70.0.3538.67
b. Các bước để phát hiện lỗi: 
i. #1: Đăng nhập vào trang http://ctct.ueh.edu.vn/
ii. #2: Nhấn vào khung tìm kiếm  
iii. #3: Tìm mục Danh sách thi trận chung kết Hội thi truyền thống Olympic các môn khoa học Mác - Lênin, tư tưởng Hồ Chí Minh lần thứ 18
c. Kết quả thực tế:  hiện nội dung không đúng
![image](https://user-images.githubusercontent.com/44269018/48066742-fbf7d280-e200-11e8-9370-a4f28ba56dcc.png)
d. Kết quả mong đợi: hiển đúng nội dung

**Comment by 31161026102** [comment]
Mình đã kiểm tra và thấy lỗi này không hợp lệ. Vẫn hiện đúng nội dung mà.Với lại theo mình lỗi này không phải lỗi chức năng.
