### ISSUE TITLE
[Nhóm#4] Lỗi tên mục liên kết không đúng ở trang http://taichuc.ueh.edu.vn

### ISSUE THREAD

**Issue by 31161021419** [UEHMonQAQC/K42#145]
a.Web Browser: Chrome- phiên bản 70.0.3538.77 (Official Build) (32-bit)
b.Các bước để phát hiện lỗi:
i. #1: truy cập trang http://taichuc.ueh.edu.vn
ii. #2: chọn mục giới thiệu, bấm chọn Chức năng nhiệm vụ
iii. #3: thấy ở dòng hiện thị tham chiếu các mục, xuất hiện mục chức năng nhiệm
vụ phòng trước mục chức năng nhiệm vụ
c. Kết quả thực tế
Tên mục liên kết không hợp lý khi hiển thị
d. Kết quả mong đợi:
Hiển thị đúng tên mục
![t](https://user-images.githubusercontent.com/44299187/48073683-dd4e0780-e211-11e8-9223-a01f0272fca3.png)

**Comment by PhamHanhMai** [comment]
<img width="931" alt="ahihi" src="https://user-images.githubusercontent.com/44106460/48079978-2d7f9680-e21f-11e8-9842-88aa3022627c.PNG">
Xin Chào, Mai đã check và Mai đã thử một thao tác khác tương tự lỗi các bạn nêu ra, ở "Cơ cấu tổ chức" (Giới thiệu --> Cơ cấu tổ chức), tuy nhiên Mai thấy phần mà mục liên kết dẫn đến là hàng chữ đen như hình trên của Mai đã khoanh, tương tự ở "Chức năng nhiệm vụ", nghĩa là theo thao tác các bạn đề ra thì đường link vẫn dẫn đúng đến nơi cần tìm. Lỗi này không hợp lệ nhé nhóm :(
