### ISSUE TITLE
[Nhóm#4] Lỗi không hiển thị đúng số trang thể hiện ở trang http://taichuc.ueh.edu.vn/ 

### ISSUE THREAD

**Issue by 31161021419** [UEHMonQAQC/K42#164]
a.Web Brower: Chrome - Phiên bản 70.0.3538.77 (Official Build) (32-bit)
b.Các bước phát hiện lỗi:
i.     #1:Truy cập trang: http://taichuc.ueh.edu.vn
ii.    #2:  ở trang chủ, kéo xuống phía dưới chọn  mục  thi ghép
iii.   #3:   Trang thông tin thi ghép hiện ra, chọn “Danh sách thi hết môn ngày 11/11/2018 tại TP. Hồ Chí Minh”
iv.   #4:  kéo chọn xem trang ở trong danh sách, thì thấy khi đặt con trỏ xem ở vị trí trang đầu tiên thì ở dưới khung hiển thị số trang lại là đang ở trang ⅖ trang, tương tự như kéo xuống trang cuối cùng là vị trí ⅘ trang
c. Kết quả thực tế:  Làm cho người nhìn khó hiểu 
d. Kết quả mong đợi:Hiển thị đúng vị trí trang đang xem để tránh gây hiểu nhầm
![untitled](https://user-images.githubusercontent.com/44299187/48138963-f5885a00-e2d7-11e8-8c74-50f64c07cd58.png)
![untitled](https://user-images.githubusercontent.com/44299187/48139000-0afd8400-e2d8-11e8-9d2e-2c0a9512cb51.png)
![untitled](https://user-images.githubusercontent.com/44299187/48139021-18b30980-e2d8-11e8-9031-48ebe4213cbc.png)
![untitled](https://user-images.githubusercontent.com/44299187/48139040-249ecb80-e2d8-11e8-867f-9cbf5029b21e.png)

**Comment by PhamHanhMai** [comment]
Xin Chào, Mai đã check và không thấy lỗi như nhóm đã nêu ra :( 
![image](https://user-images.githubusercontent.com/44106460/48147482-fc1fcd00-e2e9-11e8-971c-325f4d6e2964.png)
![image](https://user-images.githubusercontent.com/44106460/48148867-60905b80-e2ed-11e8-8955-b62d2e2a83b9.png)
