### ISSUE TITLE
[Nhóm#9] Lỗi giao diện -  LỖI GIAO DIỆN về chính tả chữ - ở trang http://lms.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161021925** [UEHMonQAQC/K42#18]
a) Web browser : Google Chrome 70.0.3538.67
 b) Các bước để phát hiện lỗi
i.# 1: Đăng nhập bằng tài khoản sinh viên vào trang http://lms.ueh.edu.vn/ 
ii.# 2: Kéo xuống cuối trang bên dưới các khóa học sẽ thấy lỗi hiện ra
c) Kết quả thực tế: 
Xuất hiện chữ "Xam tất cả các khóa học"
![image](https://user-images.githubusercontent.com/44269018/47839976-459e8280-dde7-11e8-8a9b-3cfc749c0ec6.png)
d) Kết quả mong đợi:
Tốt nhất nên xuất hiện chữ đúng chính tả, sẽ không gây khó chịu cho người sử dụng.

**Comment by 31161026102** [comment]
Mình đã kiểm tra lỗi và nhận thấy lỗi này bị trùng với lỗi  #173 của k41
