### ISSUE TITLE
[Nhóm#4] Lỗi sai cỡ chữ sai khoảng cách ở trang http://taichuc.ueh.edu.vn/ 

### ISSUE THREAD

**Issue by 31161021419** [UEHMonQAQC/K42#186]
a.Web Brower: Chrome - Phiên bản 70.0.3538.77 (Official Build) (32-bit)
b.Các bước phát hiện lỗi:
i.     #1:Truy cập trang: http://taichuc.ueh.edu.vn
ii.    #2:  ở trang chủ, kéo xuống chỗ mục thông báo mới
iii.   #3:   Nhấn chọn thông báo ngày 8/11/2018
c. Kết quả thực tế: hiển thị nội dung với cỡ chữ lớn, cách khoảng lớn giữa các dòng
d. Kết quả mong đợi: Hiển thị nội dung với cỡ chữ vừa vặn, dễ nhìn, khoảng cách hợp lý
![o](https://user-images.githubusercontent.com/44299187/48239315-01237000-e401-11e8-924f-685a4c576696.png)

**Comment by PhamHanhMai** [comment]
Xin Chào, Mai đã check tuy nhiên theo Mai đây là nội dung cần nhấn mạnh, (1 tin vui, 1 lời thông báo) thì việc chỉnh cỡ chữ lớn hơn nhằm tăng tính chú ý, nhấn mạnh cho người xem, vì vậy đây không phải lỗi hợp lệ nha nhóm :(
