### ISSUE TITLE
[Nhóm#4] Lỗi canh lề trái của chữ  http://taichuc.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161021419** [UEHMonQAQC/K42#187]
a.Web Brower: Chrome - Phiên bản 70.0.3538.77 (Official Build) (32-bit)
b.Các bước phát hiện lỗi:
i.     #1:Truy cập trang: http://taichuc.ueh.edu.vn
ii     #2: Chọn mục  giới thiệu và chọn chức năng nhiệm vụ
iii    #3: Kéo xuống mục truy cập nhiều thấy ở hàng chữ Thông tin tốt nghiệp canh lề trái không chuẩn như các mục Tuyển sinh ,Thời khóa biểu -lịch thi, Điểm thi hết môn ….
iv   #4: Kết quả thực tế : Hàng chữ canh lề trái chưa chuẩn 
v   #5: Kết quả mong muốn : Tất cả các hàng chữ được canh lề trái bằng nhau
![o](https://user-images.githubusercontent.com/44299187/48239383-3def6700-e401-11e8-8e70-61245478d196.png)

**Comment by PhamHanhMai** [comment]
Xin Chào, Mai đã check tuy nhiên tất cả các hàng này đều được căn trái dựa theo hình symbol (và hình symbol cũng có kích cỡ dài, ngắn khác nhau) nên hàng chữ kéo theo có độ lệch khác nhau. Nhóm có thể sử dụng Word để kiểm chứng, khi sử dụng symbol mình không thể chỉnh hàng chữ phía sau thẳng đều theo được nên lỗi này không hợp lệ nha nhóm 4 ơi :( 
![image](https://user-images.githubusercontent.com/44106460/48251248-8e7fb800-e433-11e8-80fc-712850c69e15.png)
