### ISSUE TITLE
[Nhóm#6] Lỗi chức năng - Lỗi Không tảI ảnh   - Ở trang http://se.ueh.edu.vn/vi/ 

### ISSUE THREAD

**Issue by 31161025123** [UEHMonQAQC/K42#190]
a.Web Browser: Chorme - Phiên bản 69.0.3497.100  
b.Các bước để phát hiện lỗi:
i.#1: Truy cập trang http://se.ueh.edu.vn/vi/
ii.#2: Click vào Cựu sinh viên chọn Công đồng Khoa Kinh tế
c.Kết quả thực tế: Ảnh không được tải lên
![untitled](https://user-images.githubusercontent.com/44266273/48244867-cd166380-e39c-11e8-96cc-49bfd1dd2d23.png)
d.Kết quả mong đợi: Ảnh được tảI lên

**Comment by thuphuongpupu** [comment]
Chào các bạn nhóm 6. Mình đã kiểm tra và xác nhận đây không phải là lỗi chức năng. Đây là lỗi giao diện- Không hiện thị hình ảnh. Các bạn xem xét và gắn gẵn labels khác nhé <3.
