### ISSUE TITLE
[Nhóm#6] Lỗi chức năng - Lỗi Chuyển đổI ngôn ngữ   - Ở trang http://se.ueh.edu.vn/vi/ 

### ISSUE THREAD

**Issue by 31161025123** [UEHMonQAQC/K42#191]
a.Web Browser: Chorme - Phiên bản 69.0.3497.100  
b.Các bước để phát hiện lỗi:
i.#1: Truy cập trang http://se.ueh.edu.vn/vi/
ii.#2: Kéo xuống Tin tức và Sự kiện
iii.#3: Kéo lên đầu trang chọn ngôn ngữ Tiếng Anh để xem
iv.#4: Kéo xuống News và Event
c.Kết quả thực tế: Không cập nhật đầy đủ thông tin khi chuyển từ ngôn ngữ Tiếng Việt sang Tiếng Anh hoặc ngược lại
![untitled](https://user-images.githubusercontent.com/44266273/48244904-09e25a80-e39d-11e8-9e7f-cea7c7eabde6.png)
![untitled](https://user-images.githubusercontent.com/44266273/48244918-1ebeee00-e39d-11e8-8919-545529d83142.png)
d.Kết quả mong đợI: Cập nhật đầy đủ thông tin khi chuyển từ ngôn ngữ Tiếng Việt sang Tiếng Anh hoặc ngược lại

**Comment by thuphuongpupu** [comment]
Chào các bạn nhóm 6. Mình đã kiểm tra và xác nhận đây là lỗi không hợp lệ.
Thứ nhất : Nếu chuyển ngôn ngữ ngay từ đầu (ở phía trên đầu trang) sang tiếng anh, nó sẽ ra 1 page mới dành cho các du học sinh, các bạn có thể thấy sự khác biệt ở thanh công cụ, và Nội dung sẽ có sự khác biệt. 
Thứ 2: Việc chuyển đổi ngôn ngữ không hề ảnh hưởng đến nội dung và việc cập nhập thông tin cả, bạn dùng click vào TRANSLATE ở cuối trang, toàn bộ thông tin đều được cập nhật đầy đủ.
Các bạn xem xét lại lỗi dùm mình nhé <3, Cảm ơn các bạn
