### ISSUE TITLE
[Nhóm#6] Lỗi chức năng - LỗI Không tìm được thông tin  - Ở trang http://se.ueh.edu.vn/vi/  

### ISSUE THREAD

**Issue by 31161025123** [UEHMonQAQC/K42#192]
a.Web Browser: Cốc Cốc (.Ink)
b.Các bước để phát hiện lỗi:
i.#1: Truy cập trang http://se.ueh.edu.vn/vi/  
ii.#2: Nhập Tìm kiếm: Cơ hội học bổng
iii.#3: Bấm tìm kiếm
c.Kết quả thực tế: Không tìm được thông tin học bổng
![image](https://user-images.githubusercontent.com/44266273/48252479-b5010d00-e3b9-11e8-8dd7-4c1b91b83b91.png)
![image](https://user-images.githubusercontent.com/44266273/48252489-b9c5c100-e3b9-11e8-9140-0f80106634b3.png)
d.Kết quả mong đợi:  Tìm được thông tin học bổng

**Comment by thuphuongpupu** [comment]
Chào nhóm 6. Mình đã kiểm tra và xác nhận.Lỗi không hợp lệ.
Thực tế khi gõ vào ô tìm kiếm " Cơ hội học bổng" vẫn tìm thấy kết quả mong muốn.
Các bạn xem xét lại nhé <3.
