### ISSUE TITLE
[ Nhóm#1] - Lỗi giao diện - Lỗi font chữ - Ở trang  http://spf.ueh.edu.vn/vi/lecturers

### ISSUE THREAD

**Issue by 31161021131** [UEHMonQAQC/K42#2]
a. Web Browser: Chorme - Phiên bản 69.0.3497.100
b. Các bước để phát hiện lỗi:
i. #1: Truy cập trang http://spf.ueh.edu.vn/vi
ii.#2: Mở mục Nhân sự
iii.#3: Kéo xuống dưới vị trí stt thứ 20,21
c. Kết quả thực tế:Phần đề mục phụ trách của giảng viên bên trên không in đậm như giảng viên bên dưới
![capture](https://user-images.githubusercontent.com/44297212/47775813-5c7ba100-dd23-11e8-96d2-3f59f816cd78.PNG)

d. Kết quả mong đợi: Các phần đề mục nên được in đậm đồng đều

**Comment by vuthanhchau** [comment]
Xin chào, mình thấy phần đề mục ở đây chia làm 2 loại là "phụ trách các môn"(không in đậm) và "phụ trách các đầu việc" (in đậm). Nhóm có thể xem các mô tả về giảng viên khác để so sánh. Nên mình nghĩ rằng đây không phải lỗi giao diện nhé.

**Comment by vuthanhchau** [comment]
Xin chào, mình nghĩ đây không phải lỗi giao diện vì phần thông tin này là người dùng tự nhập vào nên không có sự giống nhau giữa các phần. Do đó, lỗi này không liên quan đến hệ thống.
