### ISSUE TITLE
[Nhóm#6] Lỗi chức năng - Lỗi tìm kiếm kết quả - Ở trang https://ilacs.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161025123** [UEHMonQAQC/K42#210]
a.Web Browser: Cốc cốc
b.Các bước để phát hiện lỗi:
i.#1: Truy cập trang https://ilacs.ueh.edu.vn/
ii.#2: Click vào "GIỚI THIỆU'' chọn "Đôi dòng về ILACS"
iii.#3: Kéo xuống chọn button "Tầm nhìn và Sứ mệnh"
iv.#4: Kéo xuống chọn button "Giảng viên nước ngoài"
Tìm thấy nội dung Giảng viên nước ngoài
v: #5: Search trên thanh tìm kiếm" Giảng viên nước ngoài"
c.Kết quả thực tế: Không tìm được kết quả
![untitled](https://user-images.githubusercontent.com/44266273/48490123-8def7480-e7d9-11e8-890a-cc2c08197d69.png)
![untitled](https://user-images.githubusercontent.com/44266273/48490066-6d271f00-e7d9-11e8-88df-bbee8c6a5556.png)
d.Kết quả mong đợi: Tìm được kết quả nội dung Giảng viên nước ngoài

**Comment by thuphuongpupu** [comment]
Chào các bạn nhóm 6. Mình đã kiểm tra vẫn tìm thấy kết quả "giảng viên nước ngoài". Lỗi không hợp lệ nha.Nhóm kiểm tra lại nhé <3
