### ISSUE TITLE
[Nhóm#6] Lỗi chức năng- Lỗi tìm kiếm kết quả - Ở trang https://ilacs.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161025123** [UEHMonQAQC/K42#211]
a.Web Browser: Cốc cốc
b.Các bước để phát hiện lỗi:
i.#1: Truy cập trang https://ilacs.ueh.edu.vn/
ii.#2: Search trên thanh tìm kiếm "Khóa học XỬ LÝ KHỦNG HOẢNG TRONG TRUYỀN THÔNG"
c.Kết quả thực tế: Không tìm kiếm được thông tin khóa học
![untitled](https://user-images.githubusercontent.com/44266273/48490766-00ad1f80-e7db-11e8-81cd-547f6ecb887e.png)
![untitled](https://user-images.githubusercontent.com/44266273/48490887-3a7e2600-e7db-11e8-944e-206b75698cc3.png)
d.Kết quả mong đợi: Tìm kiếm được thông tin khóa học

**Comment by thuphuongpupu** [comment]
Chào các bạn nhóm 6. Mình đã kiểm tra và xác nhận, đây không là lỗi chức năng nha. Lỗi không hợp lệ. Các bạn có thể kéo xuống dưới có thể tìm thấy khóa học nha.
