### ISSUE TITLE
[Nhóm #11] - Lỗi không đăng nhập được ở trang http://khkt.ueh.edu.vn/

### ISSUE THREAD

**Issue by cuongnguyen998** [UEHMonQAQC/K42#225]
a. Web Browser: Google Chrome Phiên bản 70.0.3538.77 (Phiên bản Chính thức) (64 bit)
b. Các bước để phát hiện lỗi:
i.#1. Truy cập vào trang http://khkt.ueh.edu.vn/
ii.#2. Chọn "Tổ chức thi" --> "Đăng ký tham gia coi thi"
![loicn 8](https://user-images.githubusercontent.com/22628428/48629839-48a39080-e9ed-11e8-9d64-26db0e45f2b4.png)
iii.#3.Điền thông tin vào ô Tên đăng nhập và Mật khẩu, sau đó bấm "Đăng nhập"
c.Kết quả thực tế
Không thể đăng nhập. Nút "Đăng nhập" không điều hướng đến một trang nào khác để xử lý chức năng đăng nhập. Không hiển thị thông báo cho người dùng
![image](https://user-images.githubusercontent.com/22628428/48629985-a1732900-e9ed-11e8-80d8-00d27ae195c2.png)

d.Kết quả mong đợi
Có thể đăng nhập được

**Comment by 31161023527** [comment]
Lỗi này bị trùng với nhóm 10 rồi nhé
