### ISSUE TITLE
[ Nhóm#1] Lỗi phi chức năng– Lỗi không thông báo sau khi đăng nhâp -Ở trang http://nxb.ueh.edu.vn

### ISSUE THREAD

**Issue by 31161021131** [UEHMonQAQC/K42#237]
a.	Web Browser: Chorme - Phiên bản 69.0.3497.100
b.	 Các bước để phát hiện lỗi:
i.#1: Truy cập trang: http://nxb.ueh.edu.vn 
ii.#2: Chọn mục Thành viên
iii.#3: Chọn Signed in with Google
![1](https://user-images.githubusercontent.com/44297212/48930893-f2bb7500-ef25-11e8-9472-f01f056749d9.PNG)
iv.4#: đăng nhập bằng tài khoản google của UEH 
c. Kết quả thực tế: Sau khi đăng nhập xong bấm vào thành viên vẫn chưa đăng nhập được và không thông báo thành công hay không
![2](https://user-images.githubusercontent.com/44297212/48930936-25656d80-ef26-11e8-9f3b-b9903212f2c1.PNG)
d. kết quả mong đợi:Phải có thông báo sau khi đăng nhập có thành công hay không

**Comment by vuthanhchau** [comment]
Hi nhóm, lỗi này không phải là lỗi phi chức năng, mình dẫn link một số nhóm k41 có nội dung tương tự để nhóm tham khảo (lưu ý: thầy đã closed những issue này và xác nhận ko hợp lệ) 
https://github.com/UEHMonQAQC/K41/issues/185
https://github.com/UEHMonQAQC/K41/issues/145
