### ISSUE TITLE
[Nhóm #3] Lỗi phi chức năng - Lỗi bảo mật ở trang http://mark.bit.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161023717** [UEHMonQAQC/K42#238]
a. Web Browser: Chorme - Phiên bản 70.0.3538.77
b. Các bước để phát hiện lỗi:
i.#1: Truy cập trang: http://mark.bit.ueh.edu.vn/
ii.#2: Chọn mục **Đăng ký**
iii.#3: Nhập đầy đủ thông tin
c. Kết quả thực tế: Khi nhập MSSV của K42 và khóa của K44 thì hệ thống không báo lỗi (khóa K44 không đúng với Khóa của MSSV
<img width="960" alt="1" src="https://user-images.githubusercontent.com/44312505/48932449-885b0280-ef2e-11e8-9f27-c25efee930a8.png">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/44312505/48932450-8c872000-ef2e-11e8-9014-854cd254251f.png">
d. kết quả mong đợi: Hệ thống phải báo lỗi ví dụ là khóa này phải là của K42.

**Comment by khueyeuqaqc** [comment]
Belo, theo ý kiến tui thì lỗi này phù hợp với chức năng hơn. Vì nó không cho thấy là bảo mật mà chỉ là thiếu chức năng kiểm tra thông tin hợp lệ. 
Team xem xét lại thử nha <3
