### ISSUE TITLE
[Nhóm#1] Lỗi phi chức năng – Lỗi không đồng nhất - Ở trang http://kqm.ueh.edu.vn/dao-tao-thac-si/%postname%.html/dao-tao-thac-si

### ISSUE THREAD

**Issue by 31161021131** [UEHMonQAQC/K42#241]
a. Web Browser: Chorme - Phiên bản 70.0.3538.77
b. Các bước để phát hiện lỗi:
i. #1: Truy cập trang http://kqm.ueh.edu.vn/
ii. #2: Vào mục Đào tạo
iii. #3: Vào mục Đào tạo sau đại học
iv. #4: Vào mục Thạc sĩ thương mại
v. #5: Kéo xuống dưới đến mục chương trình đào tạo
c. Kết quả thực tế: Lỗi không đồng nhất trong việc sử dụng ngôn ngữ “Tiếng anh” và “Tiếng việt”
![gg](https://user-images.githubusercontent.com/44297212/48934886-4e8ef980-ef38-11e8-8407-e782a980c99b.PNG)
d. Kết quả mong đợi : Đồng nhất về ngôn ngữ trên web

**Comment by vuthanhchau** [comment]
Hi nhóm, theo mình lỗi này là lỗi giao diện nha, nhóm xem xét thay đổi lại label giúp mình nhé.
