### ISSUE TITLE
[Nhóm #3] Lỗi phi chức năng - Lỗi bảo mật ở trang http://mark.bit.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161023717** [UEHMonQAQC/K42#242]
a. Web Browser: Chorme - Phiên bản 70.0.3538.77
b. Các bước để phát hiện lỗi:
i. #1: Truy cập trang http://mark.bit.ueh.edu.vn/
ii. #2: Nhấp vào **Đăng ký**
iii. #3: Điền không đúng các mục như Họ tên, MSSV, Khóa, Lớp
<img width="960" alt="5" src="https://user-images.githubusercontent.com/44312505/48935363-12f52f00-ef3a-11e8-89f2-dbe8c34fede3.png">
c. Kết quả thực tế: Đăng ký thành công và xác nhận email với những thông tin sai
<img width="960" alt="6" src="https://user-images.githubusercontent.com/44312505/48935489-7b441080-ef3a-11e8-968b-5b9e7e3995dc.png">
d. Kết quả mong đợi: Hệ thống phải báo lỗi hoặc không cho đăng ký .

**Comment by khueyeuqaqc** [comment]
Belo, theo ý kiến tui thì lỗi này phù hợp với chức năng hơn. Vì nó không cho thấy là bảo mật mà chỉ là thiếu chức năng kiểm tra thông tin hợp lệ.
Team xem xét lại thử nha <3
