### ISSUE TITLE
[Nhóm#6] Lỗi giao diện - Lỗi font chữ - Ở trang http://ilacs.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161025123** [UEHMonQAQC/K42#244]
a.Web Browser: Chorme - Phiên bản 69.0.3497.100
b.Các bước để phát hiện lỗi:
i.#1: Truy cập trang http://ilacs.ueh.edu.vn/
ii.#2: click vào KHÓA HỌC chọn "CEO ĐÀI LOAN"
![untitled](https://user-images.githubusercontent.com/44266273/48941722-47271a80-ef4f-11e8-89e8-2adc7cd9b879.png)

c.Kết quả thực tế: font chữ căn lề không đồng nhất
d.Kết quả mong đợi: font chữ căn lề đồng nhất

**Comment by thuphuongpupu** [comment]
Chào các bạn nhóm 6. Mình đã kiểm tra và xác nhận. Đây không phải là lỗi giao diện.Lỗi không hợp lệ.
Các bạn xem lại nhé.
