### ISSUE TITLE
[Nhóm#4]Lỗi không canh chuẩn ở trang http://alumni.ueh.edu.vn/category/tin-tuc/

### ISSUE THREAD

**Issue by 31161021419** [UEHMonQAQC/K42#28]
a. Web Browser: Chorme -Phiên bản 48.0.2564.116 m
b. Các bước để phát hiện lỗi:
i. #1: Truy cập trang http://alumni.ueh.edu.vn/ ,  sau đó vào mục tin tức 
ii. #2: Kéo xuống thấy hiện trên màn hình hình ảnh bị lệch , không canh chuẩn 
c. Kết quả thực tế: (đã chiếu hình)
d. Kết quả mong đợi: Hình ảnh được canh đều nhau 
![untitled h](https://user-images.githubusercontent.com/44299187/47853654-fd488a00-de11-11e8-92ac-fac545e283d3.png)

**Comment by PhamHanhMai** [comment]
![image](https://user-images.githubusercontent.com/44106460/47877784-4a971c80-de4f-11e8-92b7-7840362c335b.png)
Xin Chào, Mai nghĩ là do bố cục được chia làm 3 cột dọc đều nhau, nội dung của từng cột dọc trước đó tùy phần có nội dung chủ đề dài hoặc nội dung chủ đề ngắn (như hình) nên phần hình ảnh của nội dung sau từng cột dọc bị chênh lệch theo chiều ngang khác nhau, nên đây không được xem là lỗi hợp lệ nha nhóm 4 :(

**Comment by 31161021419** [comment]
Nếu  như vậy khi kéo xuống sẽ rất khó cho người đọc , như trang youth , nó rât sngay ngắn mạc dù có cái ngắn cái dài . Mai coi lại giúp nhóm với
![default](https://user-images.githubusercontent.com/44299187/47909751-6a682800-dec3-11e8-82bd-76730fcbffa8.png)

**Comment by PhamHanhMai** [comment]
sorry nhóm , Lỗi này hợp lệ nhưng Mai check lại khóa trước thì bị trùng nha ra. 
https://github.com/UEHMonQAQC/K41/issues/48
