### ISSUE TITLE
[Nhóm#11] - Lỗi định dạng văn bản ở trang http://daotao.ueh.edu.vn

### ISSUE THREAD

**Issue by cuongnguyen998** [UEHMonQAQC/K42#39]
a.	Web browser: Yandex Browser 18.10.0.2724
b.	Các bước phát hiện:
i.#1.	Truy cập trang http://daotao.ueh.edu.vn
ii.#2.	Trỏ chuột vào tab Biểu mẫu và cẩm nang sinh viên
iii.#3.	Click vào mục Cẩm nang sinh viên
c.	Kết quả thực tế: khác biệt về cách định dạng của hai mục cùng cấp
![loi 8](https://user-images.githubusercontent.com/22628428/47867261-9a67ea80-de33-11e8-963f-9ffb3fbed3f5.png)
d.	Kết quả mong muốn: chỉnh sửa cho đồng nhất

**Comment by 31161023527** [comment]
Trùng với nhóm 6
