### ISSUE TITLE
[NHÓM#3] Lỗi giao diện - Lỗi chữ bị tràn khỏi khung ở trang - ở trang http://tckt.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161023717** [UEHMonQAQC/K42#43]
a. Web Browser: Chorme - Phiên bản 70.0.3538.77
b. Các bước để phát hiện lỗi:
i. #1: Truy cập trang http://tckt.ueh.edu.vn/
ii. #2: Nhấp vào tab Qui trình
c. Kết quả thực tế: Chữ bị tràn ra ngoài khung

<img width="960" alt="chu tran" src="https://user-images.githubusercontent.com/44312505/47897402-329db800-dea4-11e8-9cf2-8de2fddfb677.png">

 
d. Kết quả mong đợi: Chữ hiện thị đúng theo căn lề

**Comment by khueyeuqaqc** [comment]
Hi team, Khuê xác nhận đây là lỗi hợp lệ nha!

**Comment by khueyeuqaqc** [comment]
Hi team, Khuê đã check lỗi và hợp lệ. Tuy nhiên, Khuê thấy lỗi này đã đc K40 kiếm rồi team ơi! 
https://github.com/UEHMonQAQC/K40/issues/2

**Comment by khueyeuqaqc** [comment]
@31161023717
