### ISSUE TITLE
[NHÓM#3] - Lỗi giao diện - Lỗi chữ tràn - Ở trang http://tckt.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161023717** [UEHMonQAQC/K42#44]
a.	Web Browser: Google Chrome 70.0.3538.77
b.	Các bước để phát hiện lỗi: 
i.	#1: Truy cập vào trang http://tckt.ueh.edu.vn/
ii.	#2: Click vào phần Giới thiệu
c.	Kết quả thực tế: Lỗi chữ tràn ra ngoài
![1](https://user-images.githubusercontent.com/44312505/47897638-29611b00-dea5-11e8-9f86-09d6c1da77c1.png)

d.	Kết quả mong đợi: Chữ nằm đúng với căn lề của khung

**Comment by khueyeuqaqc** [comment]
Lỗi này cũng là bug trùng nè :( @31161023717 
https://github.com/UEHMonQAQC/K40/issues/72
