### ISSUE TITLE
[NHÓM#3] - Lỗi giao diện - Lỗi kích thước hình ảnh - Ở trang http://tckt.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161023717** [UEHMonQAQC/K42#45]
a.	Web Browser: Google Chrome 70.0.3538.77
b.	Các bước để phát hiện lỗi:
i.  #1: Truy cập vào trang http://tckt.ueh.edu.vn/
ii.#2: Click vào phần Giới thiệu
c.	Kết quả thực tế: Lỗi kích thước hình ảnh
![1](https://user-images.githubusercontent.com/44312505/47898231-92e22900-dea7-11e8-84a7-2402c21586c6.png)

 
d.	Kết quả mong đợi: Hình ảnh được điều chỉnh vừa khích với khung nội dung

**Comment by khueyeuqaqc** [comment]
Chào các bạn, mình đã check và xác nhận là có lỗi như mô tả. 
Tuy nhiên, lỗi này bị trùng với K40. 
https://github.com/UEHMonQAQC/K40/issues/41 
@31161023717
