### ISSUE TITLE
[Nhóm #3] Lỗi giao diện - Lỗi font chữ không đồng nhất - ở trang http://tckt.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161023717** [UEHMonQAQC/K42#50]
a. Web Browser: Chorme - Phiên bản 70.0.3538.77
b. Các bước để phát hiện lỗi:
i. #1: Truy cập trang http://tckt.ueh.edu.vn/
ii. #2: Nhấp vào tab **Qui trình**
ii. #3: Chọn mục **Hướng dẫn đăng nhập trang web, tra cứu thu nhập**
iii #4: Trượt xuống khoảng giữa trang
c. Kết quả thực tế: Các font chữ hiển thị không đồng nhất (vài chữ thì được in đậm)
 
<img width="960" alt="font chu" src="https://user-images.githubusercontent.com/44312505/47898736-b5754180-dea9-11e8-963f-87bdaa84dbd1.png">

 
d. Kết quả mong đợi: Các chữ phỉa được đồng nhất với nhau

**Comment by khueyeuqaqc** [comment]
hi team, Khuê đã check những không phát hiện lỗi font nha
