### ISSUE TITLE
[Nhóm #3] Lỗi giao diện - Lỗi hiện thị thời gian không đồng nhất - ở trang http://mark.bit.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161023717** [UEHMonQAQC/K42#54]
a.Web browser : Chorme - Phiên bản 70.0.3538.77
b.Các bước để phát hiện lỗi:
i.#1: Truy cập trang http://mark.bit.ueh.edu.vn/
ii.#2: Nhấp vào tab **Dashboard**
ii.#3: Kéo xuống dưới cùng
c. Kết quả thực tế: Các thông tin về ngày tháng và giờ của mục thời điểm không đồng bộ với nhau về khoảng cách. Có lúc phần thời gian xuống hàng (màu đỏ) và có lúc không xuống hàng (màu xanh).
 
<img width="752" alt="1" src="https://user-images.githubusercontent.com/44312505/47898981-b9ee2a00-deaa-11e8-8a93-8d46f46bf54d.png">

d.Kết quả mong đợi: Phần thời gian nên xuống hàng ở tất cả các dòng hoặc không xuống hàng ở tất cả các dòng để được đồng bộ và đẹp mắt hơn.

**Comment by khueyeuqaqc** [comment]
Xin chào team, mình test và không thấy nó bị lỗi.

**Comment by khueyeuqaqc** [comment]
![name](https://user-images.githubusercontent.com/44106642/47946135-1fd5c280-df3a-11e8-89e1-a404774d0180.png)

**Comment by khueyeuqaqc** [comment]
![1](https://user-images.githubusercontent.com/44106642/47946166-7e9b3c00-df3a-11e8-9a94-b3e72fcee374.png)
Kiểm tra lại giúp mình nha.
