### ISSUE TITLE
[NHÓM 12] - LỖI GIAO DIỆN - LỖI ĐỊNH DẠNG ĐỀ MỤC TRANG DAOTAO.UEH.EDU.VN

### ISSUE THREAD

**Issue by 31161022848** [UEHMonQAQC/K42#57]
I. Lỗi 1 GUI

Lỗi Giao diện (Định dạng đề mục không đồng nhất) 
Web Browser:  Google Chrome 69.0.3497.100
Các bước để phát hiện lỗi:
1.	Truy cập vào trang web http://daotao.ueh.edu.vn/ 
2.	Nhấp vào mục “Biểu mẫu và cẩm nang sinh viên”
3.	Chọn mục “Cẩm nang sinh viên”
4.	Kéo xuống và nhìn vào 2 đề mục “Cẩm nang sinh viên” và “Các qui định và hướng dẫn của trường Đại học Kinh tế TP.HCM”
5.	Kết quả thực tế: Định dạng đề mục không đồng nhất. 
6.	Kết quả mong đợi: Hiển thị các đề mục được định dạng đồng nhất về size, font chữ, màu chữ, …

![image](https://user-images.githubusercontent.com/44227075/47915275-ec148180-ded4-11e8-9b0a-8ee576baf78d.png)

**Comment by 31161024766** [comment]
Huệ kiểm tra đăng bài theo mẫu này nhé
a. Web Browser:
b. Các bước để phát hiện lỗi:
i. #1:
ii. #2:
iii. ...
c. Kết quả thực tế
d. Kết quả mong đợi

**Comment by 31161024766** [comment]
Sau khi kiểm tra thì nhóm bị trùng lỗi với nhóm 6 nhé. Nhóm kiểm tra lại giúp mình
https://github.com/UEHMonQAQC/K42/issues/13
