### ISSUE TITLE
[NHÓM 12] - LỖI GIAO DIỆN - LỖI THIẾT KẾ TRANG CHỦ TRANG DAOTAO.UEH.EDU.VN

### ISSUE THREAD

**Issue by 31161022848** [UEHMonQAQC/K42#60]
IV. Lỗi 4 GUI

Lỗi Giao diện (khung tin tức không đồng kích cỡ)

a. Web Browser:Google Chrome 69.0.3497.100
b. Các bước để phát hiện lỗi:
i. #1:Truy cập vào trang web http://daotao.ueh.edu.vn/
ii. #2:Nhìn vào “trang chủ”
iii. #3: Kéo xuống dưới cuối \trang.
c. Kết quả thưc tế: độ dài của các khùng thông tin không đồng nhất
d. Kết quả mong đợi: hiển thị độ dài của các khung thông tin bằng nhau

![image](https://user-images.githubusercontent.com/44227075/47916002-34cd3a00-ded7-11e8-8548-28534044fa26.png)

**Comment by 31161024766** [comment]
Huệ đăng lại bài theo mẫu này nhé :) (chú ý phần hình ảnh của kết quả thực tế hay mong đợi nhé)
a. Web Browser:
b. Các bước để phát hiện lỗi:
i. #1:
ii. #2:
iii. ...
c. Kết quả thực tế
d. Kết quả mong đợi

**Comment by 31161024766** [comment]
đăng lại bài mới luôn nhé Huệ. Không chỉnh sửa trên này nữa nhé :)
