### ISSUE TITLE
[NHÓM 14] - Lỗi Giao Diện - Lỗi hiển thị của Bộ lọc của trang vieclam.ueh.edu.vn

### ISSUE THREAD

**Issue by 31161020183** [UEHMonQAQC/K42#61]
a. Web Browser: Firefox Quantum 63.0 
b. Các bước để phát hiện lỗi:
 i. #1: Vào trang vieclam.ueh.edu.vn
 ii. #2: Nhấn vào chức năng Xem tất cả danh sách công việc 
iii. #3: Nhấn vào tab Nhóm ngành 
iv. #4: Nhấn vào tab Kinh nghiệm 
c. Kết quả thực tế: Chữ ở hai tab bị chèn lên nhau
![vieclam1](https://user-images.githubusercontent.com/44268473/47920151-f12cfd00-dee3-11e8-866b-2e0ce3f82ae2.png)

d. Kết quả mong đợi: Hai tab xổ ra riêng biệt và không bị chèn chữ lên nhau.

**Comment by vuthanhchau** [comment]
Xin chào, mình test trên nhiều thiết bị với cùng một môi trường thì không ghi nhận bug như mô tả nhé. 
![image](https://user-images.githubusercontent.com/44151860/47923119-27ba4600-deeb-11e8-8a64-1101235a62b2.png)

**Comment by vuthanhchau** [comment]
Xin chào, mình test trên nhiều thiết bị với cùng một môi trường thì không ghi nhận bug như mô tả nhé.
 
![image](https://user-images.githubusercontent.com/44151860/47923183-4c162280-deeb-11e8-8f88-309c392b68f5.png)
