### ISSUE TITLE
[Nhóm#1] - Lỗi giao diện - Lỗi căn lề - Ở trang http://nxb.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161021131** [UEHMonQAQC/K42#7]
a. Web Browser: Chorme - Phiên bản 70.0.3538.77 
b. Các bước để phát hiện lỗi:
i. #1: Truy cập trang  http://nxb.ueh.edu.vn/
ii. #2: Mở đến mục Sách 
iii. #3: Chọn vào “ Hỏi về sản phẩm này”
c. Kết quả thực tế: Lỗi căn lề 
![5](https://user-images.githubusercontent.com/44297212/47776250-8c777400-dd24-11e8-8b09-f218ac1344e6.PNG)
d. Kết quả mong đợi: Cần có khoảng cách giữa chữ và hình ảnh

**Comment by vuthanhchau** [comment]
Xin chào, nhìn chung thì mình vẫn có thể xem được chữ và hình ảnh rõ ràng nên mình không tính lỗi này nhé.
