### ISSUE TITLE
[Nhóm#10]Ký tự không thẳng hàng dọc ở trang http://khkt.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31161021455** [UEHMonQAQC/K42#70]
a.Web Browser: Google chrome v70.0.3538.77
b.Các bước thực hiện để phát hiện lỗi:
i. Vào trang http://khkt.ueh.edu.vn
ii.Bấm vào mục "Liên Hệ"
iii. Kéo xuống gần cuối trang
c.Kết quả thực tế:
![image](https://user-images.githubusercontent.com/44298167/47924993-a6b17d80-deef-11e8-977d-01f455961ccb.png)
d.Kết quả mong muốn:
Dòng chữ hiển thị thẳng hàng dọc như bình thường

**Comment by 31161024766** [comment]
Nhóm bị trùng lỗi với nhóm 11 nhé 
https://github.com/UEHMonQAQC/K42/issues/32
