### ISSUE TITLE
[NHÓM 14] - Lỗi Giao Diện - Lỗi giao diện của nút Danh mục 

### ISSUE THREAD

**Issue by 31161020183** [UEHMonQAQC/K42#74]
a. Web Browser: Firefox Quantum 63.0
b. Các bước để phát hiện lỗi:
i. #1: Vào trang vieclam.ueh.edu.vn
ii. #2: Tìm mục Danh mục
c. Kết quả thực tế: 3 hàng kẻ của mục Danh mục không dài ngang nhau
d. Kết quả mong đợi: 3 hàng kẻ này sẽ có chiều dài ngang nhau
![vieclam5](https://user-images.githubusercontent.com/44268473/47926392-05c4c180-def3-11e8-9cad-00528fec9201.PNG)

**Comment by vuthanhchau** [comment]
Xin chào, mình nghĩ 3 hàng kẻ của button "Danh mục" không dài bằng nhau là một ý tưởng thiết kế chứ không phải lỗi. => Lỗi này không hợp lệ!
