### ISSUE TITLE
[NHÓM 5] - Lỗi giao diện - lỗi căn lề ,bố cục ở trang web online.ueh.edu.vn

### ISSUE THREAD

**Issue by loandam1** [UEHMonQAQC/K42#86]
![4](https://user-images.githubusercontent.com/44691550/47929854-d87d1100-defc-11e8-9489-2497bf098b32.jpg)

a. Phiên bản:
Chrome : Version 70.0.3538.77 ( hình bên phải )
Microsoft Edge: Microsoft Edge 40.15063.674.0 ( hình bên trái )
b. Các bước phát hiện lỗi:
i: Truy cập trang www.online.ueh.edu.vn
ii:  Bấm chọn “Đăng nhập”, nhập vào MSSV và mật khẩu.
iii:  Bấm chọn “Ghi danh môn tự chọn”.
c. Kết quả thực tế:
- Khoanh tròn cam: Chữ nhỏ, dãn cách chưa đều và khung Chọn chương trình đào tạo khi bấm bấm vào không xổ ra.
- Khoanh tròn đỏ: Viền bảng của Chrome hơi chói, phân chia cột giữa các bảng không đều nhau, chỗ ngắn chỗ dài, không đồng nhất.
d. Kết quả mong đợi:
-	Chữ to vừa đủ cho người đọc.
-	Không cần tạo khung chọn cho “Hệ thống thông tin kinh doanh”.
-	Viền bảng ở Chrome bình thường như của Edge.
-	Chiều dài của các bảng đều như nhau.

**Comment by shouldqaqc** [comment]
Sau khi kiểm tra, lỗi này không hợp lệ
