### ISSUE TITLE
[NHÓM 5] - Lỗi giao diện - lỗi font chữ không đồng nhất-không theo thứ tự ở trang web online.ueh.edu.vn

### ISSUE THREAD

**Issue by loandam1** [UEHMonQAQC/K42#87]
![5](https://user-images.githubusercontent.com/44691550/47929904-f9ddfd00-defc-11e8-921f-791448a54aa6.jpg)
a. Phiên bản:
Chrome : Version 70.0.3538.77 (hình phải)
Microsoft Edge: Microsoft Edge 40.15063.674.0 (hình trái)
b. Các bước phát hiện lỗi:
i: Truy cập trang www.online.ueh.edu.vn
ii:  Bấm chọn “Đăng nhập”, nhập vào MSSV và mật khẩu.
iii:  Bấm chọn “Đăng ký xét tốt nghiệp”.
c. Kết quả thực tế:
Khoanh tròn cam: Các mục phụ/link liên kết ở Edge không nằm đúng vị trí như ở Chrome.
Bonus: Font chữ trong bài viết không đồng nhất, trình bày không theo thứ tự.
d. Kết quả mong muốn:
-	Link liên kết nằm đúng vị trí.
-	Bài viết được trình bày hợp lý, logic và dễ đọc dễ diểu cùng nắm bắt thông tin cho người dung hơn.

**Comment by shouldqaqc** [comment]
a. Phiên bản
b. Các bước phát hiện lỗi
    i:
    ii:
c. Kết quả thực tế
d. kết quả mong đợi

**Comment by shouldqaqc** [comment]
sau khi kiểm tra, lỗi này không hợp lệ.
